npmScopes:
  sibur:
    npmRegistryServer: "https://gitlab.mvk.com/api/v4/projects/151/packages/npm/"
    npmPublishRegistry: "https://gitlab.mvk.com/api/v4/projects/151/packages/npm/"

npmRegistries:
  //gitlab.mvk.com/api/v4/projects/151/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "366db8ccc4c557b1cae20470a1e0f9df1a111d0617055cf3a82f8b516ad1bb0e"
